# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis_ai
                                 A QGIS plugin
 QGIS AI Assistant

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-13
        copyright            : (C) 2025 by wuhan university
        email                : frk12138@gmai.com

        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys
import os

# 1. 获取当前插件的根目录 (即 qgis_ai 文件夹的绝对路径)
plugin_dir = os.path.dirname(os.path.abspath(__file__))

# 2. 将此目录插入到 Python 模块搜索路径的开头
if plugin_dir not in sys.path:
    sys.path.insert(0, plugin_dir)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgis_ai class from file qgis_ai.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_ai import qgis_ai
    return qgis_ai(iface)
