# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis_aiDockWidget
                                 A QGIS plugin
 QGIS AI Assistant

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-13
        git sha              : $Format:%H$
        copyright            : (C) 2025 by wuhan university
        email                : frk12138@gmai.com

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QColor
from qgis import processing
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.utils import iface
from qgis.core import Qgis, QgsProject, QgsMapLayer

from .chat_box import ChatBox

# 动态加载界面定义文件
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'qgis_ai_dockwidget_base.ui'))


class qgis_aiDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """构造函数"""
        super(qgis_aiDockWidget, self).__init__(parent)
        # 初始化从 Qt Designer 生成的界面
        self.setupUi(self)

        # 1. 初始化 ChatBox 控制器，传入当前窗口实例以访问 UI 控件
        self.chat_box = ChatBox(self)

        # 3. 显示初始化消息
        self.chat_box.show_initial_message()

    def closeEvent(self, event):
        """关闭插件窗口时的处理"""
        self.closingPlugin.emit()
        event.accept()
